### ISSUE TITLE
Server returned HTTP response code: 400 for URL: http://api.microsofttranslator.com

### ISSUE THREAD

**Issue by jrichardsz** [jrichardsz/bing-tts-api#1]
Exception in thread "main" java.io.IOException: Server returned HTTP response code: 400 for URL: http://api.microsofttranslator.com/v2/http.svc/speak?appId=TyYTiDGMltI66a4CYYlJ9e23cfF_hgv8zTXuinMoPvoY*&language=it-IT&format=audio/mp3&options=MinSize|male&text=Buongiorno%20mondo
at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1626)
at com.bing.translate.tts.sound.Audio.getAudio(Audio.java:35)
at com.bing.translate.tts.MainBingTranslate.main(MainBingTranslate.java:24)

Any idea?

**Comment by jrichardsz** [comment]
This is because the token "appId" has expired.
If you open the url error , shows:
###########################
Argument Exception
Method: Speak()
Parameter: appId
Message: The token has expired Parameter name: appId
message id=5217.V2_Rest.Speak.3515BE90
###########################
A workaround is : 
- Open your browser
- go to  : http://www.bing.com/translator/default.aspx?mkt=es-us
- enter a word in the input text
- open the developer mode and check network tab
- press sound button
- detect the request http, something like : 
  http://api.microsofttranslator.com/v2/http.svc/speak?appId=T3UpY5q7jZX7uZ668qIP3JkjhTEGseS0v3VBQtB-1Eaw*&language=es-ES&format=audio/mp3&options=MinSize|male&text=hola
- so the appId is : appId=T3UpY5q7jZX7uZ668qIP3JkjhTEGseS0v3VBQtB-1Eaw*
- just change in test class.

Today I will fix this in order to get automatically this appId

Please if you want, clone my repo and fix it. After send me a pull request :+1: 

Regards.

**Comment by jrichardsz** [comment]
I created a appId extractor. This get automatically appId :)
